- java/com/spun/util/ClassUtils.java
- java/com/spun/util/ObjectUtils.java
- java/com/spun/util/introspection/ClassGetter.java
- java/com/spun/util/tests/ClassUtilsTest.java
- java/com/spun/util/tests/TestUtils.java
- java/org/approvaltests/ReporterFactory.java
- java/org/approvaltests/namer/JUnitStackTraceNamer.java
We crafted the tool to work with Groovy & Grails together, Thanks!
> Approvals to work with Groovy & Grails

- approvaltests/src/main/doc/ApprovalTests - GettingStarted.md
- approvaltests/src/main/java/org/approvaltests/reporters/macosx/DiffPrograms.java
- approvaltests/src/main/java/org/approvaltests/reporters/windows/IntelliJCommunityReporter.java
- approvaltests/src/main/java/org/approvaltests/reporters/windows/IntelliJUltimateReporter.java
- approvaltests/src/main/java/org/approvaltests/reporters/windows/WindowsDiffReporter.java
This branch and pr is built on pr #42 done by @TobseF with some fixes and cleanups.
I could not find a easy way to amend that pull request so i created a new one.
I have tested the changes by hand on my windows machine using toolbox installation of intellij.
> Intellij reporter for windows.

- approvaltests/src/main/java/org/approvaltests/reporters/intellij/Edition.java
- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJCommunityReporter.java
- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJPathResolver.java
- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJUltimateReporter.java
- approvaltests/src/main/java/org/approvaltests/reporters/intellij/Version.java
- approvaltests/src/main/java/org/approvaltests/reporters/macosx/DiffPrograms.java
- approvaltests/src/main/java/org/approvaltests/reporters/windows/IntelliJCommunityReporter.java
- approvaltests/src/main/java/org/approvaltests/reporters/windows/WindowsDiffReporter.java
- approvaltests/src/test/java/org/approvaltests/reporters/tests/GenericDiffReporterTest.java
I did some clean up and thought it would be good to move the code into a non platform specific package. I would like to make the reporter to work on linux, and mac.
I also moved inner classes into their own class files now when there is a parent package for them.
If you like me to remove the commit that ignores the tests, just ping me.
> Intellij refactor

- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJPathResolver.java
@isidore i hope the change is small enough for you to be able to accept it by it self.
I found out that the program suffix was hardcoded and only supported windows.
> Fix binary suffix for intellij reporter, targeting linux (maybe mac)

- approvaltests-hadoop/pom.xml
See https://stackoverflow.com/questions/12444663/hadoop-mrunit-throws-exception#12485705
> fix: add classifier to mrunit dependency to resolve it from maven central

- README.md
> d mention compatibility in readme

- .github/workflows/test.yml
- README.md
- README.source.md
- approvaltests-util/docs/Features.md
- approvaltests-util/docs/StringUtils.md
- approvaltests/docs/Configuration.md
- approvaltests/docs/Features.md
- approvaltests/docs/README.md
- approvaltests/docs/Reporters.md
> github action & markdown

- .github/workflows/test.yml
- approvaltests-util/src/test/java/com/spun/util/parser/tests/VelocityUtilsTest.java
- approvaltests/src/main/java/org/approvaltests/utils/WithTimeZone.java
> fix flaky test

- README.md
- README.source.md
- approvaltests-util/src/main/java/com/spun/util/ByteArrayDataSource.java
- approvaltests-util/src/main/java/com/spun/util/DatabaseConfiguration.java
- approvaltests-util/src/main/java/com/spun/util/database/DatabaseLifeCycleUtils.java
- approvaltests-util/src/main/java/com/spun/util/database/automaticsetter/PkeyVariableSetter.java
- approvaltests-util/src/main/java/com/spun/util/io/CommaDelimitedFileParser.java
- approvaltests-util/src/main/java/com/spun/util/servlets/BasicServlet.java
- approvaltests-util/src/test/java/com/spun/util/servlets/tests/MockHttpServletResponse.java
- approvaltests/src/main/java/org/approvaltests/namer/ApprovalResults.java
- approvaltests/src/main/java/org/approvaltests/namer/MultipleFilesLabeller.java
- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJPathResolver.java
- approvaltests/src/main/java/org/approvaltests/writers/ApprovalXmlWriter.java
- todo.txt
> try with resources

- approvaltests/docs/mdsource/Features.source.md
- approvaltests/src/main/java/org/approvaltests/Approvals.java
- approvaltests/src/main/java/org/approvaltests/awt/AwtApprovals.java
> Extracted AwtApprovals

- approvaltests-util/src/main/java/com/spun/util/constants/SpunConstants.java
- todo.txt
> r deleted dead code + update todo list for next session

- approvaltests-tests/src/test/java/org/approvaltests/namer/AttributeStackSelectorTest.java
- approvaltests-tests/src/test/java/org/approvaltests/namer/AttributeStackSelectorTest.unrollLambda.approved.txt
- approvaltests-tests/src/test/java/org/approvaltests/reporters/UseReporterTest.java
- approvaltests-util/src/main/java/com/spun/util/ArrayUtils.java
- approvaltests-util/src/main/java/com/spun/util/LambdaThreadLauncher.java
- approvaltests-util/src/main/java/com/spun/util/tests/TestUtils.java
- approvaltests/src/main/java/org/approvaltests/ReporterFactory.java
- approvaltests/src/main/java/org/approvaltests/namer/AttributeStackSelector.java
- approvaltests/src/test/java/org/approvaltests/namer/JUnit5StackTraceNamerTest.java
- todo.txt
> junit5 UseReporter

- .github/workflows/test-windows.yml
> github action for running tests on windows

- approvaltests/src/test/java/org/approvaltests/scrubbers/RegExScrubberTest.replaceRandomNumber.approved.txt
> t updated approved file

- approvaltests-tests/src/test/java/org/approvaltests/OptionsTest.java
- approvaltests-tests/src/test/java/org/approvaltests/OptionsTest.verifyFileExtension.approved.html
- approvaltests-tests/src/test/java/org/approvaltests/approvers/FileApproverTest.java
- approvaltests/docs/Features.md
- approvaltests/src/main/java/org/approvaltests/Approvals.java
- approvaltests/src/main/java/org/approvaltests/core/Options.java
- approvaltests/src/main/java/org/approvaltests/writers/ApprovalTextWriter.java
- approvaltests/src/main/java/org/approvaltests/writers/ApprovalXmlWriter.java
- todo.txt
Options allow definition of file extension
> Options allow definition of file extension

- approvaltests-tests/src/test/java/org/approvaltests/OptionsTest.java
- approvaltests-tests/src/test/java/org/approvaltests/customApproval.approved.html
- approvaltests-tests/src/test/java/org/approvaltests/customApproval.approved.txt
- approvaltests/src/main/java/org/approvaltests/Approvals.java
- approvaltests/src/main/java/org/approvaltests/core/Options.java
- approvaltests/src/main/java/org/approvaltests/namer/ApprovalNamer.java
- approvaltests/src/main/java/org/approvaltests/namer/GetApprovalName.java
- approvaltests/src/main/java/org/approvaltests/namer/GetSourceFilePath.java
- approvaltests/src/main/java/org/approvaltests/namer/NamerWrapper.java
- todo.txt
> Options.forFile custom name

- approvaltests-tests/src/test/java/org/approvaltests/ApprovalsTest.java
- approvaltests-tests/src/test/java/org/approvaltests/ApprovalsTest.testWrongCall.approved.txt
- approvaltests/src/main/java/org/approvaltests/Approvals.java
> helpmessage when using Approvals.verify(Component)

- approvaltests-tests/src/test/java/org/approvaltests/scrubbers/DateScrubberTests.java
- approvaltests-tests/src/test/java/org/approvaltests/scrubbers/DateScrubberTests.testGetDateScrubber.approved.txt
- approvaltests/src/main/java/org/approvaltests/scrubbers/DateScrubber.java
looks like I didn't open a PR on Wednesday once we were done.
> better help messages when DateScrubber fails to detect pattern

- approvaltests/pom.xml
> e bump to junit-jupiter 5.7.0

- README.source.md
update the URL to the approvaltests website
> update the URL to the approvaltests website

- approvaltests/src/main/java/org/approvaltests/reporters/intellij/IntelliJPathResolver.java
Still no idea how to test those reporters. 
Idea: We could somehow make Path injectable and use something like this: https://github.com/google/jimfs where we prepare some paths/files to be present to at least test the file walking logic.
> issue #147 done/wip ?!

- .github/workflows/test.yml
> . e add Java 24 to CI
